version: '3.9'
services:
  #MinIO Service
  minio:
    image: 'quay.io/minio/minio:latest'
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
    volumes:
      - 'minio-data:/data'
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - bot-diario

  # MinIO Create Bucket Service
  minio-createbucket:
    image: minio/mc
    restart: 'no'
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
        /bin/sh -c "
        sleep 10;
        /usr/bin/mc config host add minio ${MINIO_SERVER_URL} ${SERVICE_USER_MINIO} ${SERVICE_PASSWORD_MINIO};
        /usr/bin/mc mb minio/typebot;
        /usr/bin/mc anonymous set public minio/typebot/public;
        exit 0;
        "
    networks:
      - bot-diario

networks:
  bot-diario:
    external: true