# docker-compose.dev.yml
version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npx", "tsx", "src/server.ts"]
    depends_on:
      - postgres

  postgres:
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  # Volumes dedicados para o ambiente de desenvolvimento
  postgres_data_dev: